### PR TITLE
Play noteblock sound while counting down to respawn.

### PR DESCRIPTION
**Pull request by TheMonBonGH**

### CODE REVIEW

**Comment by Plajer** [comment]
BLOCK_NOTE_BLOCK_PLING neither exists on 1.8.8 and 1.12.
On 1.8.8 it's NOTE_PLING and on 1.12 BLOCK_NOTE_PLING

**Comment by TheMonBonGH** [comment]
> BLOCK_NOTE_BLOCK_PLING neither exists on 1.8.8 nor 1.12.
> On 1.8.8 it's NOTE_PLING and on 1.12 BLOCK_NOTE_PLING

would using "XSound" fix that?

**Comment by TheMonBonGH** [comment]
i did a thing

**Comment by valoeghese** [comment]
This should probably be a config option

**Comment by Tigerpanzer02** [comment]
Should be made configurable and also with more sounds on other stuff...
Adding this sound for now. (Exists on XSound)

**Pull request merged**
